# Generated by Django 3.2 on 2021-04-18 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_dep', models.CharField(max_length=80)),
                ('region', models.CharField(choices=[('NT', 'NORTE'), ('CT', 'CENTRO'), ('SR', 'SUR'), ('OR', 'ORIENTE'), ('OC', 'OCCIDENTE')], default='NT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento_municipio',
            fields=[
                ('id_departamento_municipio', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_mun', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id_negocio', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_neg', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_suc', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=8)),
                ('id_departamento_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.departamento_municipio')),
                ('id_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id_queja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('queja', models.CharField(max_length=256)),
                ('id_departamento_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.departamento_municipio')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.sucursal')),
            ],
        ),
        migrations.AddField(
            model_name='departamento_municipio',
            name='id_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.municipio'),
        ),
    ]
